
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eduremus_web
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=eduremus_db
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: